# fly.toml app configuration file generated for vocal-remover on 2025-05-10T07:14:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vocal-remover'
primary_region = 'sjc'

[build]

[[mounts]]
  source = "spleeter_models"
  destination = "/root/.cache/spleeter"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
