services:
  - type: web # This will be a web service
    name: spleeter-api # You can name this whatever you like
    env: docker # We are using Docker
    dockerfilePath: ./Dockerfile # Path to your Dockerfile
    # Docker context is the root of your repo by default
    healthCheckPath: / # Enabled health check
    disk: # Spleeter models can be large and are downloaded into the container
      name: spleeter-models
      mountPath: /root/.cache/spleeter # Spleeter's default model download path
      sizeGB: 5 # Adjust size as needed (2stems ~100MB, 4stems ~100MB, 5stems ~150MB, plus base image and other files)
                # Consider the total size of all models if they are all downloaded.
    instanceType: free # Using Render's free tier for initial setup.
                         # Likely too small for Spleeter processing; upgrade will be needed.
    envVars:
      - key: PYTHON_VERSION # Ensure Render uses a compatible Python if not relying solely on Docker's Python
        value: "3.9" # Matches your Dockerfile base image
      # - key: PORT # Render injects PORT automatically; Gunicorn in Dockerfile uses it.
      #  value: "8080" # This line can usually be removed.
      # Add any other environment variables your spleeter_api.py might need here.
      # For example, if you add API keys or other configurations.
